export const Templates = {
  "v10_rhp": {
    "headers": [
      "CBLLP07.01",
      "RHPLP07.01",
      "",
      ""
    ],
    "field": {
      "dateStart": 5,
      "dateLen": 4,
      "accountStart": 9,
      "accountLen": 19,
      "diarioStart": 29,
      "diarioLen": 2,
      "numDocStart": 38,
      "numDocLen": 9,
      "descStart": 59,
      "descLen": 61,
      "amountEnd": 126,
      "amountFieldLen": 15,
      "dcPos": 127,
      "entidadeStart": 128,
      "entidadeLen": 4,
      "tipoEntidadeStart": 140,
      "tipoEntidadeLen": 1,
      "vatCodeStart": 141,
      "vatCodeLen": 8,
      "reflexoStart": 151,
      "reflexoLen": 19,
      "yearStart": 221,
      "yearLen": 4
    }
  },
  "v_gcp": {
    "headers": [
      "CBLLE10.03",
      "GCPLE10.03",
      "",
      ""
    ],
    "field": {
      "dateStart": 5,
      "dateLen": 4,
      "accountStart": 9,
      "accountLen": 19,
      "diarioStart": 29,
      "diarioLen": 2,
      "contadorStart": 34,
      "contadorLen": 10,
      "tipoDocStart": 44,
      "tipoDocLen": 5,
      "numDocEnd": 58,
      "numDocLen": 10,
      "descStart": 59,
      "descLen": 50,
      "amountEnd": 126,
      "amountFieldLen": 18,
      "dcPos": 127,
      "entidadeStart": 128,
      "entidadeLen": 12,
      "tipoEntidadeStart": 140,
      "tipoEntidadeLen": 1,
      "vatCodeStart": 141,
      "vatCodeLen": 10,
      "reflexoStart": 151,
      "reflexoLen": 20,
      "yearStart": 221,
      "yearLen": 4,
      "docDateStart": 304,
      "docDateLen": 8,
      "refDocStart": 312,
      "refDocLen": 40,
      "masterYearStart": 666,
      "masterYearLen": 4,
      "masterDocumentStart": 671,
      "masterDocumentLen": 30,
      "masterSequenceStart": 701,
      "masterSequenceLen": 4,
      "masterAmount1End": 726,
      "masterAmount2End": 744,
      "masterAmount3End": 762,
      "masterAmountLen": 18,
      "masterCurrencyStart": 763,
      "masterCurrencyLen": 3,
      "masterDcPos": 766,
      "fiscalDate1Start": 767,
      "fiscalDate2Start": 775,
      "fiscalDate3Start": 783,
      "nifStart": 791,
      "nifLen": 9,
      "nomeStart": 811,
      "nomeLen": 150,
      "paisStart": 961,
      "paisLen": 2,
      "taxaIvaStart": 1024,
      "taxaIvaLen": 5,
      "nifRecapStart": 1062,
      "nomeRecapStart": 1082,
      "paisRecapStart": 1232,
      "nifTerceiroStart": 1234,
      "nomeTerceiroStart": 1254,
      "paisTerceiroStart": 1404
    }
  }
} as const;
